config/routes.rb
Nytech::Application.routes.draw do

  # routes for joins tables
  resource  :user_jobs, only: [:create, :destroy]
  resources :object_skills, only: [:create, :update, :destroy] 
  resources :user_articles, only: [:create, :destroy]
  resources :taggings, only: [:create, :destroy]
  resources :user_articles, only: [:create, :destroy]
  resources :user_job_preapprovals, only: [:create, :destroy]
  
  # models that don't have views
  resources :tags, only: [:index, :create, :destroy]  
  resources :taxonomies, only: [:index]
  resources :images, only: [:create, :destroy] do 
    member { post :remove }
  end
  
  # models in progress
  resources :prospects, only: [:index]
  resources :groups
  resources :chatrooms, only: [:index, :create, :destroy, :show]
  resources :messages, only: [:create, :destroy]

  # models with views
  resources :articles do 
    member { put :increase_views }
    member { put :increase_recs }
    resources :comments, only: [:create]
  end
  resource  :session, only: [:new, :create, :destroy]
  resources :skills, only: [:index, :create, :update, :destroy] do
    collection { get :name }
    collection { get :dept }
    collection { get :sub_dept }
  end

  resources :users do 
    member { post :delete_snapshot }
    resources :articles, only: [:create, :update, :new, :index, :edit]
  end  

  resources :investors do
    member { post :delete_snapshot }
  end    

  resources :companies, only: [:index, :new, :update, :show, :destroy] do
    member { put :add_section }
    member { post :delete_snapshot }
    collection { get :autocomplete_fields }
    resources :jobs, only: [:create]
    resources :articles, only: [:create, :update, :new, :index]
  end

  resources :jobs, only: [:show, :index, :new, :update, :destroy, :edit] do 
    member { get :wolfpack_option }
    member { get :edit_company }
    member { post :import_data }
    member { put :update_req_skills }
    member { get :forward_form }
    collection { get :flip_view }
  end
  
  namespace :admin do 
    resources :jobs, :companies, only: [:index, :show, :new] do 
      collection { get :send_listings_form }
      collection { get :preapproval_applicants }
    end
    resources :prospects, only: [:index] do 
      collection { post :create_from_link }
    end
    resources :users, only: [:edit, :update]
    resources :skills, only: [:index, :create, :destroy]
  end
  
  # authentication
  match '/signup',                   to: 'users#new', via: :get
  match '/login',                    to: 'sessions#new', via: :get
  match '/logout',                   to: 'sessions#destroy', via: :delete
  match '/auth/:provider/callback',  to: 'sessions#create', via: [:get, :post]

  # mailers
  match '/send_listings',            to: 'admin/jobs#send_listings', via: :post
  match '/forward_job',              to: 'jobs#forward_job', via: :post
  match '/contact_us',               to: 'shared#contact_us', via: :get
  match '/send_contact_us_email',    to: 'shared#send_contact_us_email', via: :post

  match '/all_activity',             to: 'shared#all_activity', via: :get
  match '/welcome_to_wolfpack',      to: 'shared#welcome_to_wolfpack', via: :get
  match '/pending_applicant',        to: 'shared#pending_applicant', via: :get

  match '/',                         to: 'articles#index', constraints: { subdomain: /blog/ }, via: :get
  root to: 'jobs#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :company
  belongs_to :investor
  
  has_many :taggings    
  has_many :tags, through: :taggings, source: :tag
  
  has_many :user_articles  
  has_many :users, through: :user_articles, source: :user

  has_many :article_topics
  has_many :topics, through: :article_topics, source: :topic

  has_many :article_comments
  has_many :comments, through: :article_comments, source: :comment

  has_many :images

  include Recommend

  def self.my_articles(current_user)
    current_user.articles
  end

  def first_sentence
  	return nil if self.body.nil?
  	self.body.split(' ')[0..30].join(' ')
  end

  def author 
    self.users.first
  end

  def increase_view_count
    self.views = self.views + 1
    self.save
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :set_this_tab, only: [:index, :show]

  # def index
  #   if request.subdomain == 'blog'
  #     @user = User.find(77)
  #     @articles = @user.articles
  #   elsif params[:company_id]
  #     @company = Company.find(params[:company_id])
  #     @articles = @company.articles
  #   else
  #     @articles = Article.all
  #   end
  # end

  # def new
  #   @article = Article.create
  #   @user = current_user
  #   UserArticle.create(article_id: @article.id, user_id: @user.id)
  #   redirect_to edit_user_article_url(@user, @article)
  # end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      UserArticle.create(article_id: @article.id, user_id: current_user.id)
      topic = create_or_return_topic(params[:topic_id], @article.id) if params[:topic_id]
      tag = create_or_return_tag(topic.id, params[:tag_id]) if (params[:tag_id] && topic)
      create_article_tag(@article.id, tag.id) if tag
    end
    
    redirect_to articles_url
  end


  def index
    @comment = Comment.new

    if params['new_article'] == 'true'
      @new_article = Article.new
    end

    if params['my_articles'] == 'true'
      @articles = Article.my_articles(current_user)
    else
      @articles = Article.all
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end  

  def update
    @article = Article.find(params[:id])
    
    if @article.update_attributes(article_params)
      if params[:company_id]
        company = Company.find(params[:company_id])
        redirect_to company_url(company)
      elsif params[:investor_id]
        investor = Investor.find(params[:investor_id])
        redirect_to investor_url(investor)
      else
        render @article
      end
    end
  end
  
  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to :back
  end

  def increase_views
    @article = Article.find(params[:id])
    if @article.increase_view_count
      redirect_to articles_url, status: 303
    end
  end

  def increase_recs
    @article = Article.find(params[:id])
    if @article.increase_recs
      redirect_to articles_url, status: 303
    end
  end
    
  #---------------------------------------------------------------------------------------
  private
  
  def article_params
    params.require(:article).permit(:title, :body, :link, :author_id, 
      :tag_id, :company_id, :investor_id, :views, :recs)
  end

  def set_this_tab
    set_tab('articles')
  end

  def create_or_return_topic(topic_id, article_id)
    if topic_id && topic_id.to_i != 0
      @topic = Topic.find(topic_id.to_i)
      ArticleTopic.create(article_id: article_id, topic_id: topic_id.to_i)
    elsif topic_id && topic_id.to_i == 0
      if !Topic.where('name @@ ?', topic_id).empty?
        @topic = Topic.where('name @@ ?', topic_id).first
        ArticleTopic.create(article_id: article_id, topic_id: @topic.id)
      else
        @topic = Topic.new(name: topic_id)

        if @topic.save
          ArticleTopic.create(article_id: article_id, topic_id: @topic.id)
        end
      end
    end

    return @topic
  end


  def create_or_return_tag(topic_id, tag_id)
    if tag_id && tag_id.to_i != 0
      @tag = Tag.find(tag_id.to_i)
      TopicTag.create(topic_id: topic_id, tag_id: tag_id.to_i)
    elsif tag_id && tag_id.to_i == 0
      if !Tag.where('tag_name @@ ?', tag_id).empty?
        @tag = Tag.where('tag_name @@ ?', tag_id).first
        TopicTag.create(topic_id: topic_id, tag_id: @tag.id)
      else
        @tag = Tag.new(tag_name: tag_id)

        if @tag.save
          TopicTag.create(topic_id: topic_id, tag_id: @tag.id)
        end
      end
    end

    return @tag
  end  
  
  def create_article_tag(article_id, tag_id)
    Tagging.create(article_id: article_id, tag_id: tag_id)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  # get rid of anything that isn't a letter or number, replace spaces with dashes
  def normalize_string(str)
    new_str = str.downcase.gsub(/[^a-z0-9\s]/, '').strip.gsub(/\s/, '-')
    return new_str
  end  

  # get all article tags, return as one string (with spaces)
  def insert_tag_ids(article)
    article.tags.map { |tag| "tag-id-#{tag.id}" }.join(' ')
  end	
  
  def find_tagging_id(article, tag)
    tagging = Tagging.where(article_id: article.id, tag_id: tag.id).first
    return tagging.id
  end

  def add_placeholders_if_nil(section, text)
    return text unless text.nil? || text.empty?
    
    case section
    when 'title'
      return '<h1>Title</h1>'
    when 'body'
      return '<p>Body</p>'
    end
  end    
  
end

app/views/articles/#_article.html.erb
<% article = locals[:article] %>
<% this_table = locals[:this_table] %>

<% if article.tags.any? %>
	<% section_class = normalize_string(article.tags[0].tag_name) %>
<% end %>

<div class="article-wrapper editable" 
	data-article-id="<%= article.id %>" 
	data-table="<%= this_table %>">	

	<%= render './shared/editor' %>

	<% section_title = add_placeholders_if_nil('title', article.title) %>	

	<div class="title" contenteditable="true" data-placeholder="Enter Title">
		<%= raw(section_title) %>
	</div>

	<div class="link" contenteditable="true" data-placeholder="Enter Link">
		<%= article.link || 'Enter Link' %>
	</div>

	<article class="editable body" contenteditable="true" data-placeholder="Type your post">
		<% section_body = add_placeholders_if_nil('body', article.body).squish %>	
		<%= raw(section_body) %>

		<% this_image = article.images.last %>		
		<p><%= image_tag this_image.image_file.url if this_image %></p>
	</article>

	<%= render './shared/upload_image_form', locals: { article: article } %>

 	<div class="admin-options">
		<i class="fa fa-cogs"> Additional Options</i>
		<%= link_to 'Delete Article', article_url(article), method: :delete, 
				confirm: 'Sure?', class: 'delete-article-link' %>		
		<%= render './shared/tags_form', locals: { article: article } %>
		<%= render './shared/social_sharing_icons', locals: { article: article } %>
	</div>

</div>

app/views/articles/_article.html.erb
<% article = locals[:article] %>
<% this_table = locals[:this_table] %>

<li class="user-skills is-draggable article">					
	<span class="skill-icon-wrapper article left">
		<!-- <i class="<%#= icon_dept_match(job.dept) %> join-us"></i> -->
		<span class="skill-name article">
			<h1>
				<%= link_to article.title, article.link, target: '_blank', class: "article-link",
				data: { article_id: article.id } %>
			</h1>

			<h3 class="left">Posted by: <%= article.users.first.fname %></h3>
<!-- 
			<h3 class="left">
				<%#= link_to "Discuss (#{article.comments.size})", '#' %>
			</h3>
			
			<h3 class="left">
				<%#= link_to "Recommend (#{article.recs})", '#', class: "recommend-link article-#{article.id}",
					data: { article_id: article.id } %>
			</h3> -->
			
			<%# article.topics.each do |topic| %>
				<!-- <h3 class="left tag"> | <%#= topic.name %></h3> -->
			<%# end %>
			
			<%# article.tags.each do |tag| %>
				<!-- <h3 class="left tag"> | <%#= tag.tag_name.titleize %></h3> -->
			<%# end %>				
		</span>
	</span>

	<span class="comments-wrapper left">
		<h1 class="views-count article-<%= article.id %>"><%= article.views %></h1>
		<h1 class="views">Recommends</h1>
	</span>	

<!-- 	<span class="comments-wrapper left">
		<h1 class="views-count article-<%#= article.id %>"><%#= article.views %></h1>
		<h1 class="views">Comments</h1>
	</span> -->

	<span class="views-wrapper left">
		<h1 class="views-count article-<%= article.id %>"><%= article.views %></h1>
		<h1 class="views">Views</h1>
	</span>

<!-- 	<span class="howl-wrapper left">
		<%#= link_to 'Reply', '#' %>
	</span>	 -->

<%
=begin %>
	<div class="comments-wrapper">
		<%= form_for([article, @comment]) do |f| %>
			<%= f.text_field :body %>

			<%= f.submit 'Post Comment' %>
		<% end %>

		<% article.comments.each do |comment| %>
			<%= comment.body %>
		<% end %>
	</div>
<%
=end %>

</li>


<%#= render './shared/tags_form', locals: { article: article } %>

app/views/articles/_article_preview.html.erb
<% article = locals[:article] %>

<span class="left">
	<%= render './cards/company_bcard', locals: { company: article.company } %>
</span>

<div class="preview-description-wrapper article left">	
	<span class="left">
		<%= raw(article.title) %>
	</span>

	<span class="article-text left">
		<%= raw(article.first_sentence) %>
	</span>
</div>

<!-- <span class="left">
	<%#= render './cards/company_bcard', locals: { company: article.company } %>
</span> -->
	

app/views/articles/edit.html.erb
<%= render 'article', locals: { article: @article, this_table: 'articles' } %>

app/views/articles/index.html.erb
<%#= render "./layouts/inpage_navbar" %>

<div class="article-card-wrapper">
	<div class='droppable-wrapper group'>
		
		<h1>
			NYTech:
			<% Topic.all.each do |topic| %>
				<%= link_to topic.name, '#' %>
			<% end %>

			<%= link_to 'My Articles', articles_url(my_articles: true), class: 'right' %>
			<%= link_to 'New Link', articles_url(new_article: true), class: 'right' %>
		</h1>


		<ul class="skills-ul">
			<% if @new_article %>

				<%= form_for(@new_article) do |f| %>
					<li class="user-skills is-draggable">					
						<span class="skill-icon-wrapper">
							<span class="skill-name join-us">
								<%= f.text_field :title, placeholder: 'Enter Title' %>
								<%= f.text_field :link, placeholder: 'Enter Link to Article' %>
								<%= text_field_tag :topic_id, nil, placeholder: 'Topic' %>
								<%= text_field_tag :tag_id, nil, placeholder: 'Tags', class: 'add-tag' %>
							</span>
						</span>

						<%= f.submit 'Publish' %>
					</li>				
				<% end %>

<%
=begin %>				
	<% @tagging = Tagging.new %>
	<%= form_for @tagging, url: taggings_url, html: { multipart: true, 'data-article-id' => "#{article.id}" }, remote: true do |f| %>
	
		<% empty_arr = [] %>
		<% empty_arr << @tagging.tag.attributes unless @tagging.tag.nil? %>
		<%= f.hidden_field :article_id, value: article.id %>
		<i class="fa fa-tag"></i>
		<%= f.text_field :tag_id, placeholder: 'Add Tag', class: 'add-tag', 'data-pre' => empty_arr.to_json %>
		<%= f.submit 'New Tagging' %>
	<% end %>
<%
=end %>

			<% end %>

			<% @articles.each do |article| %>
					<%= render 'article', locals: { article: article, this_table: 'articles' } %>
			<% end %>
		</ul>

	</div>
</div>

app/views/articles/new.html.erb
<!-- THIS IS FOR A "FULL BLOWN" ARTICLE -->
<%#= render 'article', locals: { article: @article, this_table: 'users' } %>

<!-- FOR NOW, USERS WILL JUST POST LINKS -->
<%= render './forms/article_form', locals: { article: @article, user: @user } %>

app/views/articles/show.html.erb
<%= render "./layouts/inpage_navbar" %>

<ul class="links">
	<li>
		<%#= render 'article', locals: { article: @article, this_table: 'users' } %>
		<%= render './forms/article_form', locals: { article: @article } %>
	</li>
</ul>