config/routes.rb
Nytech::Application.routes.draw do

  # routes for joins tables
  resource  :user_jobs, only: [:create, :destroy]
  resources :object_skills, only: [:create, :update, :destroy] 
  resources :user_articles, only: [:create, :destroy]
  resources :taggings, only: [:create, :destroy]
  resources :user_articles, only: [:create, :destroy]
  resources :user_job_preapprovals, only: [:create, :destroy]
  
  # models that don't have views
  resources :tags, only: [:index, :create, :destroy]  
  resources :taxonomies, only: [:index]
  resources :images, only: [:create, :destroy] do 
    member { post :remove }
  end
  
  # models in progress
  resources :prospects, only: [:index]
  resources :groups
  resources :chatrooms, only: [:index, :create, :destroy, :show]
  resources :messages, only: [:create, :destroy]

  # models with views
  resources :articles do 
    member { put :increase_views }
    member { put :increase_recs }
    resources :comments, only: [:create]
  end
  resource  :session, only: [:new, :create, :destroy]
  resources :skills, only: [:index, :create, :update, :destroy] do
    collection { get :name }
    collection { get :dept }
    collection { get :sub_dept }
  end

  resources :users do 
    member { post :delete_snapshot }
    resources :articles, only: [:create, :update, :new, :index, :edit]
  end  

  resources :investors do
    member { post :delete_snapshot }
  end    

  resources :companies, only: [:index, :new, :update, :show, :destroy] do
    member { put :add_section }
    member { post :delete_snapshot }
    collection { get :autocomplete_fields }
    resources :jobs, only: [:create]
    resources :articles, only: [:create, :update, :new, :index]
  end

  resources :jobs, only: [:show, :index, :new, :update, :destroy, :edit] do 
    member { get :wolfpack_option }
    member { get :edit_company }
    member { post :import_data }
    member { put :update_req_skills }
    member { get :forward_form }
    collection { get :flip_view }
  end
  
  namespace :admin do 
    resources :jobs, :companies, only: [:index, :show, :new] do 
      collection { get :send_listings_form }
      collection { get :preapproval_applicants }
    end
    resources :prospects, only: [:index] do 
      collection { post :create_from_link }
    end
    resources :users, only: [:edit, :update]
    resources :skills, only: [:index, :create, :destroy]
  end
  
  # authentication
  match '/signup',                   to: 'users#new', via: :get
  match '/login',                    to: 'sessions#new', via: :get
  match '/logout',                   to: 'sessions#destroy', via: :delete
  match '/auth/:provider/callback',  to: 'sessions#create', via: [:get, :post]

  # mailers
  match '/send_listings',            to: 'admin/jobs#send_listings', via: :post
  match '/forward_job',              to: 'jobs#forward_job', via: :post
  match '/contact_us',               to: 'shared#contact_us', via: :get
  match '/send_contact_us_email',    to: 'shared#send_contact_us_email', via: :post

  match '/all_activity',             to: 'shared#all_activity', via: :get
  match '/welcome_to_wolfpack',      to: 'shared#welcome_to_wolfpack', via: :get
  match '/pending_applicant',        to: 'shared#pending_applicant', via: :get

  match '/',                         to: 'articles#index', constraints: { subdomain: /blog/ }, via: :get
  root to: 'jobs#index'
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController

  def pending_applicant
  end

  def welcome_to_wolfpack
    @applicant = current_user
  end

	def contact_us
	end

  def send_contact_us_email
  	sender_email = params[:email_info][:sender_email]
  	recipient_email = params[:email_info][:recipient_email]
  	subject_line = 'Message from Wolfpack Beta user'
  	email_body = params[:email_info][:email_body]

  	SharedMailer.contact_us(
  		sender_email,
  		recipient_email,
  		subject_line,
  		email_body
  	).deliver

    redirect_to :back
  end	

  def all_activity
    if current_user.job_settings.any? && current_user.job_settings[:key_skills] 
      @jobs = Job.return_jobs_with_key_skills(current_user).page(params[:page]).per(10) 
    elsif current_user.job_settings.any?
      @jobs = Job.return_jobs_without_key_skills(current_user).page(params[:page]).per(10)
    else
      @jobs = Job.all.page(params[:page]).per(10)
    end

    @articles = Article.all
    @users = User.all
  end

end

app/views/shared/_box_of_logos.html.erb
<% object = locals[:user] || locals[:job] || locals[:company] %>

<% if current_user.job_settings[:sub_dept] %>
	<% first_sub_dept = current_user.job_settings[:sub_dept].first %>
<% else %>
	<% first_sub_dept = 'back-end' %>
<% end %>


<div class="box-of-logos is-droppable hidden">
	<ul class="box-of-logos-ul group">

		<% Taxonomy.departments.each do |dept| %>
			<div class="dept-selector" data-dept='<%= dept.downcase %>'><%= dept %></div>

			<% skill_hash = Skill.return_skill_hash_from_dept(dept.downcase) %>

			<div class="group <%= dept.downcase %> ">
				<% skill_hash.each do |key, val_obj_arr| %>
					<% this_class = "#{key} " + "#{dept.downcase} " + "#{'hidden' if dept.downcase != 'engineer'}" %>
					<%= link_to key, '#', class: this_class, data: { selected: key } %>
				<% end %>
			</div> 

			<% skill_hash.each do |key, val_obj_arr| %>
					<% val_obj_arr.each do |skill_obj| %>
						<% next if object.tech_stack.include?(skill_obj) %>

						<% skill_icon = icon_skill_match(skill_obj.skill_name) %>

						<li class="<%= key %> <%= 'hidden' unless key == 'back-end' %> left" 
							data-skill-id="<%= skill_obj.id %>" data-object-id="<%= object.id %>" 
							data-object-class="<%= object.class.to_s.downcase %>">

							<% if skill_icon %>
								<span class="skill-icon-wrapper">
									<i class="<%= skill_icon %> skill-icon"></i>
								</span>
							<% elsif skill_obj.logo.exists? %>
								<%= image_tag(skill_obj.logo.url, class: 'is-draggable') %>
							<% else %>
								<%= render './shared/upload_logo', locals: { object: skill_obj } %>
							<% end %>
						</li>
					<% end %>
			<% end %>												
		<% end %>

	</ul>
</div>

<!-- add_new_skill_form.css.scss -->
<%= form_for(@skill) do |f| %>
	<%= f.text_field :skill_name, placeholder: 'Skill name' %>
	<%= f.text_field :skill_dept, placeholder: 'Skill dept' %>
	<%= f.text_field :skill_sub_dept, placeholder: 'Skill sub dept' %>
	<input type="textbox" name="skill[preferred_phrases][]" placeholder="preferred phrases" >
	<input type="textbox" name="skill[required_phrases][]" placeholder="required phrases">
	<%= f.submit %>
<% end %>

app/views/shared/_drag_and_drop.html.erb
<% object = locals[:user] || locals[:job] || locals[:company] %>
<% obj_class_id = object.class.to_s.downcase + '_id' %>

<!-- DROP SKILLS -->
<div class='droppable-wrapper group'>

	<h1>
	<!-- <h1 class="dark-banner"> -->
		Tech Stack
		<%= link_to 'Add Skills', '#', id: 'edit-skills', class: 'right' %>
		<%= link_to 'Done', '#', id: 'save-skills', class: 'hidden right' %>
	</h1>

	<ul class="skills-ul <%= object.class.to_s.downcase %>-<%= object.id %>">
		<% object.tech_stack.each do |skill_obj| %>
			<% object_skill = ObjectSkill.where(obj_class_id => object.id, skill_id: skill_obj.id).first %>

			<li class="user-skills is-draggable left" data-object-skill-id="<%= object_skill.id %>">
				<% skill_icon = icon_skill_match(skill_obj.skill_name) %>
				
				<% if skill_icon %>
					<span class="skill-icon-wrapper">
						<i class="<%= skill_icon %> skill-icon"></i>
						<span class="skill-name"><%= skill_obj.skill_name.titleize %></span>
					</span>
				<% else %>
					<% if skill_obj.logo.exists? %>
						<span class="skill-image">
							<%= image_tag(skill_obj.logo.url) %>
							<span class="skill-name"><%= skill_obj.skill_name.titleize %></span>
						</span>				
					<% end %>
				<% end %>
			
		<% end %>
		</li>

		<span class="add-skill hidden">
			<li id="add-skill-li" class="user-skills">+ Drag skill from below up here!</li>
		</span>
	</ul>

</div>

<!-- DRAG SKILLS -->
<% if current_user.job_settings[:sub_dept] %>
	<% first_sub_dept = current_user.job_settings[:sub_dept].first %>
<% else %>
	<% first_sub_dept = 'back-end' %>
<% end %>

<div class="box-of-logos is-droppable hidden">
	<ul class="box-of-logos-ul group">

		<span class="dept-selector-wrap">
			<% Taxonomy.departments.each do |dept| %>
				<span class="dept-selector" data-dept='<%= dept.downcase %>'>
					<%= dept %>
				</span>
			<% end %>
		</span>

		<% Taxonomy.departments.each do |dept| %>
			<% skill_hash = Skill.return_skill_hash_from_dept(dept.downcase) %>

			<div class="group <%= dept.downcase %> sub-dept-selector">
				<% skill_hash.each do |key, val_obj_arr| %>
					<% this_class = "#{key} " + "#{dept.downcase} " + "#{'hidden' if dept.downcase != 'engineer'}" %>
					<%= link_to key.gsub('-', ' ').titleize, '#', class: this_class, data: { selected: key } %>
				<% end %>
			</div> 

			<% skill_hash.each do |key, val_obj_arr| %>
					<% val_obj_arr.each do |skill_obj| %>
						<% next if object.tech_stack.include?(skill_obj) %>

						<% skill_icon = icon_skill_match(skill_obj.skill_name) %>

						<li class="<%= key %> <%= 'hidden' unless key == 'back-end' %> left is-draggable" 
							data-skill-id="<%= skill_obj.id %>" data-object-id="<%= object.id %>" 
							data-object-class="<%= object.class.to_s.downcase %>">

							<% if skill_icon %>
								<span class="skill-icon-wrapper">
									<i class="<%= skill_icon %> skill-icon"></i>
									<span class="skill-name"><%= skill_obj.skill_name.titleize %></span>
								</span>
							<% else %>
								<% if skill_obj.logo.exists? %>
									<span class="skill-image">
										<%= image_tag(skill_obj.logo.url) %>
										<span class="skill-name"><%= skill_obj.skill_name.titleize %></span>
									</span>				
								<% end %>
							<% end %>
						</li>
					<% end %>
			<% end %>												
		<% end %>
	</ul>
	
</div>

app/views/shared/_editor.html.erb
<div class="editor-class-wrapper">
	<div id="editor">
		<div id="editor-mask">
			<div class="editor-buttons">
				<button class="icon icon-bold" id="editor-b" data-command="bold">&#xf032;</button>
				<button class="icon icon-italic" id="editor-i" data-command="italic">&#xf033;</button>
				<button class="icon icon-quote" id="editor-blockquote" data-command="quote">&#xe000;</button>
				<button class="heading" id="editor-h1" data-command="h1">h1</button>
				<button class="heading" id="editor-h2" data-command="h2">h2</button>
				<button class="heading" id="editor-h3" data-command="h3">h3</button>
				<!-- <button class="heading" id="editor-h4" data-command="h4">h4</button>
				<button class="heading" id="editor-h5" data-command="h5">h5</button>
				<button class="heading" id="editor-h6" data-command="h6">h6</button> -->
				<button class="icon icon-link" id="editor-a" data-command="a">&#xe001;</button>
			</div> <!-- editor-buttons -->
			
			<div id="editor-link-field-holder">
				<input type="text" id="editor-link-field" placeholder="Type or paste link">
				<button class="icon icon-remove" id="editor-cancel" data-command="cancel">&#xf00d;</button>
			</div> <!-- editor-link-field-holder -->
		</div> <!-- editor-mask -->
	</div> <!-- editor -->
</div>

app/views/shared/_errors.html.erb
<% if object && object.errors.any? %>

	<div class="errors">
		<% object.errors.full_messages.each do |error_msg| %>
			<%= error_msg %>
		<% end %>
	</div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

app/views/shared/_social_sharing_icons.html.erb
<% article = locals[:article]%>

<div class="social-sharing">
	
	<div class="share-buttons-wrapper">

		<i class="fa fa-envelope"></i>			
	
		<div id="fb-root">
			<i class="fa fa-facebook-square">
				<% request_uri = 'http://localhost:3000/' %>
				<%= fb_share(ENV['FACEBOOK_APP_ID'], request_uri, 
					{
						display: "popup",
						link: request.original_url.gsub('localhost:3000', 'wolfpackbeta.com')
					}
				) %>
			</i>		
		</div>
	
		<!-- <i class="fa fa-linkedin-square"></i>		 -->
		<!-- <i class="fa fa-tumblr-square"></i> -->
		
		<% tweet_default_text = article.title.nil? ? '' : "Just spreading the word! Check out: #{strip_tags(article.title.squish)} #{request.original_url.gsub('localhost:3000', 'wolfpackbeta.com')}" %>

		<a href="https://twitter.com/share?text=<%= tweet_default_text %>" 
			class="popup"
			target="_blank">
			<!-- data-text='Just spreading the word! Check out: <%#= strip_tags(article.title.squish) %>' -->
			<i class="fa fa-twitter-square"></i>
		</a>	

	</div>	
		
</div>		

<script src="//platform.linkedin.com/in.js" type="text/javascript" data-url="www.google.com">
  lang: en_US
</script>

<!-- <script type="IN/Share"></script> -->

app/views/shared/_tags_form.html.erb
<% article = locals[:article] %>

<div class="add-tags-wrapper">
	<div class="existing-tags <%= article.tags.any? ? '' : 'hidden' %>">
		<ul class="article-tags-<%= article.id %> article-tags">
			<h2 class="left">Tags:</h1>
			<% article.tags.each do |tag| %>
				<li class=" existing-tag-li left" data-id="<%= find_tagging_id(article, tag) %>">
					<%= tag.tag_name %>
					<i class="fa fa-times-circle"></i>
				</li>
			<% end %>
		</ul>		
	</div>
	
	<% @tagging = Tagging.new %>
	<%= form_for @tagging, url: taggings_url, html: { multipart: true, 'data-article-id' => "#{article.id}" }, remote: true do |f| %>
	
		<% empty_arr = [] %>
		<% empty_arr << @tagging.tag.attributes unless @tagging.tag.nil? %>
		<%= f.hidden_field :article_id, value: article.id %>
		<i class="fa fa-tag"></i>
		<%= f.text_field :tag_id, placeholder: 'Add Tag', class: 'add-tag', 'data-pre' => empty_arr.to_json %>
		<%= f.submit 'New Tagging' %>
	<% end %>
</div>

app/views/shared/_upload_image_form.html.erb
<% object = locals[:obj] %>
<% article = locals[:article]%>

<div class="uploader">
	<span class="insert-image-span">
		<i class="fa fa-picture-o"></i>
		<span>Insert an Image</span>	
	</span>

	<%= form_for Image.new, html: { multipart: true } do |form| %>
		<%= form.hidden_field :article_id, value: article.id %>
		<%= form.file_field :image_file %>
		<%= form.submit "Upload Image" %>
	<% end %>
		
</div>

app/views/shared/_upload_logo.html.erb
<% object = locals[:object] %>

<div class="uploader-logo <%= 'hidden' if object.logo.exists? && object.class != Skill %>">
		<%= form_for object, url: skill_url(object), html: { multipart: true } do |f| %>
			<span class="insert-image-span">
				<span>Insert Logo for <%= object.skill_name %></span>	
				<i class="fa fa-picture-o"></i>
			</span>		
			<%= f.file_field :logo %>
			<%= f.submit %>
		<% end %>
	<%# end %>
</div>

app/views/shared/all_activity.html.erb
<%# @feed = @jobs + @articles + @users %>
<% @feed = @jobs + @articles %>

<ul class="all-activity">
	<% @feed.shuffle.each do |feed_item| %>
			<% if feed_item.class == Job %>
				<li><%= render './jobs/job_listing_preview', locals: { job: feed_item } %></li>
			<% elsif feed_item.class == Article %>
				<% next if feed_item.title.nil? || feed_item.title.empty? %>	
				<li><%= render './articles/article_preview', locals: { article: feed_item } %></li>
			<% elsif feed_item.class == User %>
				<li><%= render './users/user_preview', locals: { user: feed_item } %></li>
			<% end %>
		
	<% end %>
</ul>

app/views/shared/contact_us.html.erb
<div class="forward-form">
	<i class="fa fa-times-circle"></i>
	
  <%= form_tag send_contact_us_email_url, method: :post do %>
  	<%= text_field_tag "email_info[sender_email]", nil, placeholder: 'Enter your email' %>
    <%= text_field_tag "email_info[recipient_email]", nil, value: 'contact@wolfpackbeta.com' %>
    <%= text_area_tag "email_info[email_body]", nil, placeholder: "What's up?" %>

    <%= submit_tag "Send" %>
  <% end %>
</div>

app/views/shared/pending_applicant.html.erb
<h1>Thanks for applying!</h1>

<p>Your application is pending</p>

<p>If you have any questions contact us at contact@wolfpackbeta.com</p>

app/views/shared/welcome_to_wolfpack.html.erb
<div class="landing-page-wrapper">

	<section id="section-1">
		<div class="landing-page-bg"></div>	
		<div class="landing-page-one-wrapper">
			<h1>Find the job where you belong</h1>
			<p>Due to capacity constraints, we can only serve applicants that:</p>
			<p class="bullet">Are interested in startups in the NYC-area</p>
			<p class="bullet">Are seeking programming or design jobs</p>
			<%= link_to 'Tell me more', '#', class: 'landing-page-btn', id: 'tell-me-more' %>
		</div>
	</section>

	<section id="section-2">
		<div class="landing-page-two-wrapper">
			<h1>Who We Are</h1>
			<p>We are a team with backgrounds in programming, VC, recruiting and data science. We have one mission: to help you find a job where you will be happy.</p>
			
			<h1>What We Do</h1>
			<p>We analyze your background, skill set, and prior work history.</p>
			<p>Using a mix of sentiment analysis, machine learning, industry-based intuition and good old-fashioned manual labor, we match you to companies and careers.</p>
			<p>Out of the 1,000+ listings in our database, we will only send you the top 0.5%-2.0% matches.</p>

			<h1>What We Don't Do</h1>
			<p class="bullet">Spam you, or your friends</p>
			<p class="bullet">Share your information, with anyone, anytime, anywhere</p>
			<p class="bullet">Charge you or the hiring company. Wolfpack is currently free. Free as in beer</p>
		</div>

		<div class="landing-page-three-wrapper">
			<h1 class="header">To Get Started (Two Steps):</h1>

			<span class="step-1">
				<h2>Step 1</h2>
				<p>
					Sign in through LinkedIn
					<%= link_to "", "/auth/linkedin?origin=landing_page", class: "fa fa-linkedin-square" %>
				</p>
				<p class="or">- or - </p>
				<p>Send us your LinkedIn profile URL and email address:</p>
				<% email_provider = @applicant.email.split('@')[1] if @applicant_email %>
				<% email_value = email_provider == 'wolfpackguest.com' ? '' : @applicant.email %>
				
				<%= form_for(@applicant) do |f| %>
					<% li_url = @applicant.linkedin_url ? @applicant.linkedin_url.squish : nil %>
					<%= f.text_field :linkedin_url, value: li_url, placeholder: 'Paste LinkedIn URL' %>
					<%= f.text_field :email, value: email_value, placeholder: 'Input your email' %>
	
				</span>

				<span class="step-2">
					<h2>Step 2</h2>
					<p>Send us one-sentence (max 200 characters) about what you're looking for</p>
						<%= f.text_area :one_liner, value: @applicant.one_liner, placeholder: 'Type text here' %>
				</span>

				<%= f.hidden_field :is_applicant, value: true %>

			<h1 class="the-rest">Step 3: We'll take care of the rest</h1>
				<%= f.submit 'Done' %>
			<% end %>
			<%#= link_to "I'm Done", '#', class: 'landing-page-btn' %>
		</div>		
	</section>



</div>