config/routes.rb
Nytech::Application.routes.draw do

  # routes for joins tables
  resource  :user_jobs, only: [:create, :destroy]
  resources :object_skills, only: [:create, :update, :destroy] 
  resources :user_articles, only: [:create, :destroy]
  resources :taggings, only: [:create, :destroy]
  resources :user_articles, only: [:create, :destroy]
  resources :user_job_preapprovals, only: [:create, :destroy]
  
  # models that don't have views
  resources :tags, only: [:index, :create, :destroy]  
  resources :taxonomies, only: [:index]
  resources :images, only: [:create, :destroy] do 
    member { post :remove }
  end
  
  # models in progress
  resources :prospects, only: [:index]
  resources :groups
  resources :chatrooms, only: [:index, :create, :destroy, :show]
  resources :messages, only: [:create, :destroy]

  # models with views
  resources :articles do 
    member { put :increase_views }
    member { put :increase_recs }
    resources :comments, only: [:create]
  end
  resource  :session, only: [:new, :create, :destroy]
  resources :skills, only: [:index, :create, :update, :destroy] do
    collection { get :name }
    collection { get :dept }
    collection { get :sub_dept }
  end

  resources :users do 
    member { post :delete_snapshot }
    resources :articles, only: [:create, :update, :new, :index, :edit]
  end  

  resources :investors do
    member { post :delete_snapshot }
  end    

  resources :companies, only: [:index, :new, :update, :show, :destroy] do
    member { put :add_section }
    member { post :delete_snapshot }
    collection { get :autocomplete_fields }
    resources :jobs, only: [:create]
    resources :articles, only: [:create, :update, :new, :index]
  end

  resources :jobs, only: [:show, :index, :new, :update, :destroy, :edit] do 
    member { get :wolfpack_option }
    member { get :edit_company }
    member { post :import_data }
    member { put :update_req_skills }
    member { get :forward_form }
    collection { get :flip_view }
  end
  
  namespace :admin do 
    resources :jobs, :companies, only: [:index, :show, :new] do 
      collection { get :send_listings_form }
      collection { get :preapproval_applicants }
    end
    resources :prospects, only: [:index] do 
      collection { post :create_from_link }
    end
    resources :users, only: [:edit, :update]
    resources :skills, only: [:index, :create, :destroy]
  end
  
  # authentication
  match '/signup',                   to: 'users#new', via: :get
  match '/login',                    to: 'sessions#new', via: :get
  match '/logout',                   to: 'sessions#destroy', via: :delete
  match '/auth/:provider/callback',  to: 'sessions#create', via: [:get, :post]

  # mailers
  match '/send_listings',            to: 'admin/jobs#send_listings', via: :post
  match '/forward_job',              to: 'jobs#forward_job', via: :post
  match '/contact_us',               to: 'shared#contact_us', via: :get
  match '/send_contact_us_email',    to: 'shared#send_contact_us_email', via: :post

  match '/all_activity',             to: 'shared#all_activity', via: :get
  match '/welcome_to_wolfpack',      to: 'shared#welcome_to_wolfpack', via: :get
  match '/pending_applicant',        to: 'shared#pending_applicant', via: :get

  match '/',                         to: 'articles#index', constraints: { subdomain: /blog/ }, via: :get
  root to: 'jobs#index'
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::ApplicationController

	def index
    @jobs = []
    jobs = Job.all.sample(10)

    jobs.each do |job|
      @job_ranker = JobRanker.new(job, current_user)
      @jobs << @job_ranker.job
    end

    @jobs.sort! { |a,b| b.job_score <=> a.job_score }  
  end

  def preapproval_applicants
    @preapprovals = UserJobPreapproval.all.where_user_is_applicant
  end

  def send_listings_form
    @recipient = User.find(77)

		if current_user.job_settings.any? && current_user.job_settings[:key_skills] 
	  	@jobs = Job.return_jobs_with_key_skills(current_user).limit(30)
	  elsif current_user.job_settings.any?
	    @jobs = Job.return_jobs_without_key_skills(current_user).limit(30)
	  else
	    @jobs = Job.all.limit(30)
	  end
  end

  def send_listings
    first_name = params[:first_name]
    sender = params[:sender]
    recipient = params[:recipient]
    greeting = params[:greeting]
    first_paragraph = params[:first_paragraph]
    second_paragraph = params[:second_paragraph]
    closing_paragraph = params[:closing_paragraph]

    jobs = params[:job][:ids].map { |id| Job.find(id) }
    subject = "#{first_name}: Out of 1,000+ Listings in our 
      Database, here's #{jobs.size} We Picked For You"
    subject = subject.titleize

    if JobMailer.send_listings(
        sender,
        recipient,
        subject,
        greeting,
        first_paragraph,
        second_paragraph,
        jobs,
        closing_paragraph
      ).deliver
    end
  end 
   
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  respond_to    :html, :json
  before_filter :set_this_tab, only: [:index, :show]
  before_filter :redirect_if_applicant

  # RESTful Routes ---------------------------------------------------------------------------
  def index
    @page = params[:page]

    if params[:filter]
      @jobs = filtered_jobs(params[:filter])
    elsif current_user.job_settings.any? && current_user.job_settings[:key_skills] 
      @jobs = Job.return_jobs_with_key_skills(current_user).page(params[:page]).per(5) 
    elsif current_user.job_settings.any?
      @jobs = Job.return_jobs_without_key_skills(current_user).page(params[:page]).per(5)
    else
      @jobs = Job.all.page(params[:page]).per(5)
      respond_to do |format|
        format.html
        format.csv { render text: @jobs.to_csv }
      end      
    end

    # @jobs = Job.rank_jobs(jobs, current_user)
    # @jobs.sort! { |a,b| b.job_score <=> a.job_score }
    # @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(10)    
  end
  
  def new
    @job = Job.create!
    @user = current_user
  end

  def edit
    @job = Job.find(params[:id])
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit_company
    @job = Job.find(params[:id])
  end
  
  def create
    @company = Company.find(params[:company_id])
    @job = @company.job_listings.new(job_params)
    
    if @job.save
      @job.import_data
      redirect_to company_url(@company)
    else
      flash[:error] = "Please try again"
      render :new
    end
  end
  
  def show      
    @job = Job.find(params[:id])
  end
   
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "Job updated"
      @company = @job.listing_company
    end

    redirect_to edit_job_url(@job)
  end
  
  def destroy
    @job = Job.find(params[:id])
    @company = @job.listing_company
    @job.destroy
    redirect_to company_url(@company)
  end
  
  # NON RESTFUL ---------------------------------------------------------------------------
  def wolfpack_option
    @job = Job.find(params[:id])
  end

  def import_data
    @job = Job.find(params[:id])
    @job.import_data
    redirect_to company_url(@job.listing_company)
  end
  
  def forward_form
    @job = Job.find(params[:id])
  end

  def forward_job 
    job = Job.find(params[:job_id])
    sender_email = params[:email_info][:sender_email]
    recipient_email = params[:email_info][:recipient_email]
    subject_line = "You received a forward from #{sender_email}: #{job.title.titleize}"
    email_body = params[:email_info][:body]
    
    if JobMailer.forward_job(
      recipient_email,
      subject_line,
      email_body,
      job,
      sender_email
      ).deliver
      flash[:notice] = "Forwarded successfully"
    else
      flash[:notice] = "Please try again"
    end
    
    redirect_to jobs_url
  end
  
	#---------------------------------------------------------------------------------------
	private

  def job_params
    params.require(:job).permit(:link, :title, :full_text, :is_draft, :technical_problem_commentary,
      :company_id, :dept, :sub_dept, :years_exp, :description, key_phrases: [], req_skills: [])
  end  

  def redirect_if_applicant
    if current_user.is_applicant
      redirect_to pending_applicant_url
    end
  end

  def filtered_jobs(filter)
    @filter = filter
    case filter
    when 'viewed'
      return current_user.viewed_jobs.page(params[:page]).per(5).order('years_exp DESC')
    when 'wp-app'
      return current_user.jobs_applied_via_wolpfack.page(params[:page]).per(5).order('years_exp DESC')
    when 'bookmarked'
      return current_user.bookmarked_jobs.page(params[:page]).per(5).order('years_exp DESC')
    when 'removed'
      return current_user.removed_jobs.page(params[:page]).per(5).order('years_exp DESC')
    else
      return Job.all.page(params[:page]).per(5).order('years_exp DESC')
    end
  end

  def job_preapproved?(job)
    if current_user
      current_user.preapproved_jobs.include?(job)
    else
      return false
    end
  end

  def set_this_tab
    set_tab('jobs')  
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper

  def has_viewed_job?(job)
    return true if current_user.viewed_jobs.include?(job)
    return false
  end

  def has_applied_to_job_via_wolfpack?(job)
    return true if current_user.jobs_applied_via_wolpfack.include?(job)
    return false
  end

  def has_bookmarked_job?(job)
    return true if current_user.bookmarked_jobs.include?(job)
    return false
  end

  def has_removed_job?(job)
    return true if current_user.removed_jobs.include?(job)
    return false
  end

  def sanitize_title(title)
    ActionView::Base.full_sanitizer.sanitize(title).titleize
  end

  # NEEDS REFACTORING - EAGER LOAD THIS
  def return_subcategory(prev_category, target_category, prev_cat = nil, user = nil)
    # if user is passed in, then use that, otherwise use current user
    user = user ? user : current_user

    previous_category_array = prev_cat || user.job_settings[prev_category] 
    results_array = []
    
    if previous_category_array
      Job.all.each do |job|
        results_array << job.public_send(target_category) if previous_category_array.
          include?(job.public_send(prev_category))
      end
    end

    results_array.uniq! if results_array.any? 
    results_array.compact!
    results_array.sort!
  end  
  
  def icon_dept_match(dept)
    case dept
    when 'business'
      return 'fa fa-briefcase'
    when 'engineer'
      return 'fa fa-code'
    when 'designer'
      return 'fa fa-desktop'
    when 'sales'
      return 'fa fa-bar-chart-o'
    when 'prod. management'
      return 'fa fa-lightbulb-o'
    end      
  end

  def icon_skill_match(skill)
    case skill.downcase
    when 'php'
      return 'icon-php'
    when 'perl'
      return 'icon-perl'
    when 'c++'
      return 'icon-cplusplus'
    when 'java'
      return 'icon-java'
    when 'python'
      return 'icon-python'
    when 'ruby-on-rails'
      return 'icon-ruby'
    when 'node'
      return 'icon-nodejs'
    when 'clojure'
      return 'icon-clojure'
    when 'scala'
      return 'icon-scala'
    when 'c'
      return 'icon-c'
    when 'c#'
      return 'icon-csharp'
    when 'hadoop'
      return 'icon-hadoop'
    when 'mysql'
      return 'icon-mysql'
    when 'postgres'
      return 'icon-postgres'
    when 'redis'
      return 'icon-redis'
    when 'javascript'
      return 'icon-javascript'
    when 'html/css'
      return 'icon-html'
    when 'objective-c'
      return 'icon-iphone'
    when 'iphone'
      return 'icon-iphone'      
    when 'blackberry'
      return 'icon-blackberry'
    when 'windows-phone'
      return 'fa fa-windows'
    when 'android'
      return 'fa fa-android'
    when 'centos'
      return 'icon-centos'  
    when 'nginx'
      return 'icon-nginx'    
    when 'debian'
      return 'icon-debian'   
    when 'linux'
      return 'fa fa-linux'
    when 'github'
      return 'fa-git'
    when 'aws'
      return 'icon-aws'
    when 'heroku'
      return 'icon-heroku'  
    else              
      return nil
    end    
  end  
  
  def is_attr_checked?(obj, this_attr, val)
    obj.public_send(this_attr).include?(val)
  end
  
  def is_setting_checked?(this_attr, val, user=nil)
    # if user is passed in, then use that, otherwise use current user
    user = user ? user : current_user
    return false if user.job_settings[this_attr].nil?
    return true if user.job_settings[this_attr].include?(val.to_s.downcase)
    return false    
  end

  def is_pref_checked?(this_attr, val)
    return false if current_user.job_prefs[this_attr].nil?
    return true if current_user.job_prefs[this_attr].include?(val.to_s)
    return false    
  end
  
  def sel_or_hide(dept)
    if current_user.job_settings[:dept].nil?
      return ''
    elsif current_user.job_settings[:dept].include?(dept)
      return 'selected'
    else
      return 'hidden'
    end
  end
  
  def sortable(column, title=nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {sort: column, direction: direction}, {class: css_class}
  end

  def return_years_exp
    return current_user.job_settings[:years_exp] if current_user && current_user.job_settings[:years_exp]
  end  

  
  def description_snippet(job)
    if job.description
			job.description.split(' ')[0..200].join(' ') unless job.description.nil?
		else
		  if job.full_text
				job.full_text.split(' ')[0..200].join(' ') unless job.full_text.nil?
			end
		end
	end
	
end

app/views/admin/jobs/_form.html.erb
<div class="admin">

	<%= form_for(@job) do |f| %>
	
		<%= f.text_field :link, placeholder: 'Link to job posting' %>		
		
		<%= f.text_field :link, placeholder: 'Link to job posting' %>
	
		<%= f.submit 'Post Job' %>
	
	<% end %>
</div>

app/views/admin/jobs/_job_details.html.erb
<% job = locals[:job] %>
<% this_table = 'jobs' %>
<% this_model = 'job' %>
	
<div class="job-key-stats right">
	<p><%= link_to 'Import Data', import_data_job_url(job), method: :post %></p>
	<p><%= link_to 'Destroy job', job_url(job), method: :delete, data: { confirm: 'Sure?' } %></p>
	<p>(Job ID: <%= job.id %>)</p>

	<p>
		<span class="jobs-editable"
			contenteditable= "true"
			data-id="<%= job.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="dept">
			<%= (job.dept.nil? || job.dept.empty?) ? 'Dept Here' : job.dept.titleize %>
		</span>
	</p>
	
	<p>
		<span class="jobs-editable"
			contenteditable= "true"
			data-id="<%= job.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="sub_dept">
			<%= (job.sub_dept.nil? || job.sub_dept.empty?) ? 'SubDept Here' : job.sub_dept.titleize %>
		</span>
	</p>
	
	<p>
		<span class="jobs-editable"
			contenteditable= "true"
			data-id="<%= job.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="years_exp">
			<%= (job.years_exp.nil? || job.years_exp.to_s.empty?) ? 'Years Exp' : job.years_exp %>
		</span>
	</p>
</div>
	

<div class="job-admin-section">
		
	<p><span class="heading">Link: </span><%= link_to "#{job.link}", "#{job.link}" %></p>		
	<p>Status Code: <%= job.link_status_code %></p>

	<p>One Sentence Description:</p>
		<span class="jobs-editable"
			contenteditable= "true"
			data-id="<%= job.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="description">
			<%= (job.description.nil? || job.description.empty?) ? 'description' : sanitize(job.description) %>
		</span>
	</p>
	
	<p>Full Text:</p>
	<p>
		<span class="jobs-editable"
			contenteditable= "true"
			data-id="<%= job.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="full_text">
			<%= (job.full_text.nil? || job.full_text.empty?) ? 'Full Text Here' : sanitize(job.full_text) %>
		</span>
	</p>

</div>

app/views/admin/jobs/_listings_email_form.html.erb
<% user = locals[:user] %>

<%= form_tag send_listings_url, method: :post, class: 'email-composer' do %>
  
  <h1>Recipient Name</h1>
  <%= text_field_tag "first_name", nil, value: "#{user.fname.squish}" %>

  <h1>From:</h1>
  <%= text_field_tag "sender", nil, value: 'contact@wolfpackbeta.com' %>

  <h1>To:</h1>
  <%= text_field_tag "recipient", nil, value: user.email %>

  <h1>Greeting:</h1>
  <%= text_field_tag "greeting", 
  	"Hey #{user.fname.squish},"     
  %>

  <h1>First paragraph:</h1>
  <% this_title = user.job_settings[:dept] ? user.job_settings[:dept][0] : 'developer' %>

  <%= text_field_tag "first_paragraph",
  	"We know as #{article_helper(this_title)} you get bombarded with emails all the time. If you've received this email in error, please unsubscribe here: ",
    class: 'paragraph'
  %>

  <h1>Second paragraph:</h1>
  <%= text_field_tag "second_paragraph", 
  	"We're trying something different. Instead of throwing the kitchen sink at you, we're filtering the noise so that we don't waste your time. We thought you might be interested in some of the following:",
    class: 'paragraph'
  %>

  <h1>Jobs:</h1>
  <ul>
    <% @jobs.each do |job| %>
      <li>
        <%= check_box_tag "job[ids][]", job.id %>

        <span class="jobs-editable"
          contenteditable= "<%= editable_if_admin(current_user) %>"
          data-id="<%= job.id %>" 
          data-table="jobs"
          data-model="job"
          data-attribute="title">
          <% if job.title && !job.title.empty? %>
            <%= sanitize_title(job.title) %>
          <% else %>
            -
          <% end %>
        </span>  

        <span>@ <%= job.listing_company.name %></span>

        <span class="jobs-editable"
          contenteditable= "<%= editable_if_admin(current_user) %>"
          data-id="<%= job.id %>" 
          data-table="jobs"
          data-model="job"
          data-attribute="description">
          <% if job.description && !job.description.empty? %>
            <%= job.description %>
          <% else %>
            -
          <% end %>
        </span>    

        <%= link_to 'link', job.link, target: '_blank' %>      
               
      </li>
    <% end %>
  </ul>

  <h1>Closing paragraph:</h1>
  <%= text_field_tag "closing_paragraph", 
    "Hope we did a good job here. If we didn't, your feedback is more than welcome!",
    class: 'paragraph'
  %>  

  <%= submit_tag "Send" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div id="admin-ranked-jobs">
	<table>
		<tr>
			<th>Title</th>
			<th>Dept</th>
			<th>SubDept</th>
			<th>YearsExp</th>
			<th>Company</th>
			<th>Job Req Skills</th>
			<th>Company Tech Stack</th>
			<th>User Tech Stack</th>
			<th>Full Text</th>
			<th>Score</th>
		</tr>

		<% @jobs.each do |job| %>
			<tr class="jobs-tr">
				<td><%= job.title %></td>
				<td><%= job.dept %></td>
				<td><%= job.sub_dept %></td>
				<td><%= job.years_exp %></td>
				<td><%= job.listing_company.name %></td>
				<td><%= job.req_skills %></td>
				<td>
					<ul>
						Company Tech Stack:
						<% job.listing_company.tech_stack.each do |skill| %>
							<li><%= skill.skill_name %></li>
						<% end %>
					</ul>
				</td>
				<td>
					<ul>
						User Job Settings:
						<% current_user.job_settings[:key_skills].each do |skill| %>
							<li><%= skill %></li>
						<% end %>
					</ul>
					<br>
					<ul>
						User Tech Stack:
						<% current_user.tech_stack.each do |skill| %>
							<li><%= skill.skill_name %></li>
						<% end %>
					</ul>
				</td>
				<td class="full-text">
					<% job.full_text.split('.').each do |sentence| %>
						<%= sentence %>
						<br><br>
					<% end %>
				</td>
				<td>
					<h1>Job Score:</h1>
					<%= job.job_score %>
					<h1>JobScoreTracker</h1>
					<%= job.job_score_tracker %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

<div id="user-job-preferences">
	<% current_user.job_settings[:key_skills].each do |skill| %>
		<%= skill %>
	<% end %>
</div>

app/views/admin/jobs/new.html.erb
<%= render 'form' %>

app/views/admin/jobs/preapproval_applicants.html.erb
<% @preapprovals.each do |preapproval| %>
	<%= preapproval.job.title %>
	<%= preapproval.preapproval_applicant.fname %>
<% end %>

app/views/admin/jobs/send_listings_form.html.erb
<%= render 'listings_email_form', locals: { user: @recipient} %>