config/routes.rb
Nytech::Application.routes.draw do

  # routes for joins tables
  resource  :user_jobs, only: [:create, :destroy]
  resources :object_skills, only: [:create, :update, :destroy] 
  resources :user_articles, only: [:create, :destroy]
  resources :taggings, only: [:create, :destroy]
  resources :user_articles, only: [:create, :destroy]
  resources :user_job_preapprovals, only: [:create, :destroy]
  
  # models that don't have views
  resources :tags, only: [:index, :create, :destroy]  
  resources :taxonomies, only: [:index]
  resources :images, only: [:create, :destroy] do 
    member { post :remove }
  end
  
  # models in progress
  resources :prospects, only: [:index]
  resources :groups
  resources :chatrooms, only: [:index, :create, :destroy, :show]
  resources :messages, only: [:create, :destroy]

  # models with views
  resources :articles do 
    member { put :increase_views }
    member { put :increase_recs }
    resources :comments, only: [:create]
  end
  resource  :session, only: [:new, :create, :destroy]
  resources :skills, only: [:index, :create, :update, :destroy] do
    collection { get :name }
    collection { get :dept }
    collection { get :sub_dept }
  end

  resources :users do 
    member { post :delete_snapshot }
    resources :articles, only: [:create, :update, :new, :index, :edit]
  end  

  resources :investors do
    member { post :delete_snapshot }
  end    

  resources :companies, only: [:index, :new, :update, :show, :destroy] do
    member { put :add_section }
    member { post :delete_snapshot }
    collection { get :autocomplete_fields }
    resources :jobs, only: [:create]
    resources :articles, only: [:create, :update, :new, :index]
  end

  resources :jobs, only: [:show, :index, :new, :update, :destroy, :edit] do 
    member { get :wolfpack_option }
    member { get :edit_company }
    member { post :import_data }
    member { put :update_req_skills }
    member { get :forward_form }
    collection { get :flip_view }
  end
  
  namespace :admin do 
    resources :jobs, :companies, only: [:index, :show, :new] do 
      collection { get :send_listings_form }
      collection { get :preapproval_applicants }
    end
    resources :prospects, only: [:index] do 
      collection { post :create_from_link }
    end
    resources :users, only: [:edit, :update]
    resources :skills, only: [:index, :create, :destroy]
  end
  
  # authentication
  match '/signup',                   to: 'users#new', via: :get
  match '/login',                    to: 'sessions#new', via: :get
  match '/logout',                   to: 'sessions#destroy', via: :delete
  match '/auth/:provider/callback',  to: 'sessions#create', via: [:get, :post]

  # mailers
  match '/send_listings',            to: 'admin/jobs#send_listings', via: :post
  match '/forward_job',              to: 'jobs#forward_job', via: :post
  match '/contact_us',               to: 'shared#contact_us', via: :get
  match '/send_contact_us_email',    to: 'shared#send_contact_us_email', via: :post

  match '/all_activity',             to: 'shared#all_activity', via: :get
  match '/welcome_to_wolfpack',      to: 'shared#welcome_to_wolfpack', via: :get
  match '/pending_applicant',        to: 'shared#pending_applicant', via: :get

  match '/',                         to: 'articles#index', constraints: { subdomain: /blog/ }, via: :get
  root to: 'jobs#index'
end

app/views/cards/_company_bcard.html.erb
<% company = locals[:company] %>
<% user = locals[:user] %>

<div class="company-business-card">
	<% if !company.nil? && company.logo.exists? %>
		<%= image_tag company.logo.url %>
	<% end %>

	<% if company && (user == current_user || current_user.is_admin) %>
		<div class="uploader-logo <%= 'hidden' if company.logo.exists? %>">
			<span class="insert-image-span">
				<span>Insert Logo</span>	
				<i class="fa fa-picture-o"></i>
			</span>	
			<%= form_for company, url: company_url(company), html: { multipart: true } do |f| %>	
				<%= f.file_field :logo %>
				<%= f.submit %>
			<% end %>
		</div>
	<% end %>	
</div>

app/views/cards/_company_overview.html.erb
<% company = locals[:company] %>
<% this_table = 'companies' %>
<% this_model = this_table.singularize %>

<div class="company-overview">
	<h1><%= link_to "#{company.name}", company_url(company) %></h1>
	
	<p class="companies-editable"
		contenteditable="true"
		data-id="<%= company.id %>" 
		data-table="<%= this_table %>"
		data-model="<%= this_model %>"
		data-attribute="overview">
		<%= (company.overview.nil? || company.overview.empty?) ? '-' : company.overview %>
	</p>
</div>

app/views/cards/_company_stats.html.erb
<% company = locals[:company] %>
<% this_table = 'companies' %>
<% this_model = this_table.singularize %>

<div class="company-stats">
	<h3>
		<span>Funding:</span>
		<span contenteditable="true"
			data-id="<%= company.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="total_money_raised"
			class="companies-editable">				
			<%= (company.total_money_raised.nil? || company.total_money_raised.empty?) ? "-" : company.total_money_raised %>
		</span>
	</h3>
	<h3>
		<span>Employees:</span>
		<span contenteditable="true"
			data-id="<%= company.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="num_employees"
			class="companies-editable">				
			<%= company.num_employees.nil? ? "-" : company.num_employees %>
		</span>			
	</h3>
	<h3>
		<span>Category:</span>
		<span contenteditable="true"
			data-id="<%= company.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="category_code"
			class="companies-editable">				
			<%= (company.category_code.nil? || company.category_code.empty?) ? "-" : company.category_code %>
		</span>			
	</h3>
	<h3>
		<span>City:</span>
		<span contenteditable="true"
			data-id="<%= company.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="city"
			class="companies-editable">				
			<%= (company.city.nil? || company.city.empty?) ? "-" : company.city %>
		</span>			
	</h3>						
	<h3>
		<span>Neighborhood:</span>
		<span contenteditable="true"
			data-id="<%= company.id %>" 
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-attribute="neighborhood"
			class="companies-editable">				
			<%= (company.neighborhood.nil? || company.neighborhood.empty?) ? "-" : company.neighborhood %>
		</span>			
	</h3>			

	<% if current_user.is_admin %>
		<% if company.career_page_link %>				
			<%= link_to 'Career Page', company.career_page_link, target: '_blank' %>
		<% else %>
			<%= form_for(company) do |f| %>
				<%= f.text_field :career_page_link %>
				<%= f.submit "Submit Career Page" %>
			<% end %>		
		<% end %>	

		<% if company.company_blog_url %>	
			<span contenteditable="true"
				data-id="<%= company.id %>" 
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-attribute="company_blog_url"
				class="companies-editable">				
				<%= company.company_blog_url %>
			</span>
		<% else %>
			<%= form_for(company) do |f| %>
				<%= f.text_field :company_blog_url || '-' %>
				<%= f.submit "Submit Company Blog" %>
			<% end %>		
		<% end %>	

		<% if company.tech_blog_url %>		
			<span contenteditable="true"
				data-id="<%= company.id %>" 
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-attribute="tech_blog_url"
				class="companies-editable">			
				<%= company.tech_blog_url || '-' %>
			</span>
		<% else %>
			<%= form_for(company) do |f| %>
				<%= f.text_field :tech_blog_url %>
				<%= f.submit "Submit Tech Blog" %>
			<% end %>		
		<% end %>	

	<% else %>
		<!-- <h3>Twitter: <%#= company.twitter_username || "" %></h3> -->
		<!-- <h3><%#= best_in_place company, :career_page_link %></h3> -->
		<%= link_to "Go to #{company.name}'s career page", company.career_page_link, target: '_blank' %>
	<% end %>
	
</div><!-- company-stats -->

app/views/cards/_recent_work.html.erb
<h2 class="dark-banner">
  Recent Work
</h2>

<p>Summary</p>

app/views/cards/_references.html.erb
<h1 class="dark-banner">
  References
</h1>

<h2>Name</h2>
<p>Summary</p>

app/views/cards/_user_bcard.html.erb
<% user = locals[:user] %>
<% this_table = 'users' %>
<% this_model = this_table.singularize %>
<% is_editable = bcard_editable?(user) %>

<div class="business-card-wrapper">

  <div class="info">

		<div class="full-name">	
		  <h1 class="h1-fname users-editable"
				contenteditable="<%= is_editable %>"
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-id=<%= user.id %> 
				data-attribute='fname'>
				<% if action_name == 'show' %>
					<%= (user.fname.nil? || user.fname.empty?) ? 'First Name' : user.fname %>
				<% elsif action_name == 'index' %>
					<%= link_to "#{user.fname}", user_url(user) %>
				<% end %>
		  </h1>
		
		  <h1 class="h1-lname users-editable" 
				contenteditable="<%= is_editable %>"
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-id=<%= user.id %> 
				data-attribute='lname'>
				<% if action_name == 'show' %>
					<%= (user.lname.nil? || user.lname.empty?) ? 'Last Name' : user.lname %>
				<% elsif action_name == 'index' %>
					<%= link_to "#{user.lname}", user_url(user) %>				
				<% end %>					
		  </h1>
		</div>
		
		<div class="bcard-title">
			<h2>I'm a</h2>
		  <h2 id="title"
				class="users-editable"
				contenteditable="<%= is_editable %>"
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-id=<%= user.id %> 
				data-attribute='title'>
		
				<%= (user.title.nil? || user.title.empty?) ? 'Title' : user.title %>
		  </h2>
		</div>
	
		<div class="bcard-employer">
			<h2>at </h2>
			<h2 id="employer" data-id="<%= user.id %>">
				<%= (user.employer.nil? || user.employer.name.empty?) ? 'Placeholder' : user.employer.name %>
			</h2>
		</div>
		
		<div class="bcard-location">
			<h2>I work in </h2>
		  <h2 id="location" 
				class="users-editable"		
				contenteditable="<%= is_editable %>"
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-id=<%= user.id %> 
				data-attribute='location'>
				<%= (user.location.nil? || user.location.empty?) ? 'Location' : user.location %>
		  </h2>
		</div>	

		<div class="bcard-location-two">
			<h2>I'm from </h2>
		  <h2 id="location-two"
				class="users-editable"		 
				contenteditable="<%= is_editable %>"
				data-table="<%= this_table %>"
				data-model="<%= this_model %>"
				data-id=<%= user.id %> 
				data-attribute='location_from'>
				<%= (user.location_from.nil? || user.location_from.empty?) ? 'Location' : user.location_from %>		  
			</h2>
		</div>	

  </div>
	
	<%= image_tag user.avatar.url if user.avatar.exists? %>

	<% if (current_user == user || current_user.is_admin) %>
		<div class="uploader <%= 'hidden' if user.avatar.exists? %>">
			<span class="insert-image-span">
				<i class="fa fa-picture-o"></i>
				<span>Insert Image</span>	
			</span>	

			<%= form_for user, url: user_url(user), html: { multipart: true} do |f| %>
				<%= f.file_field :avatar %>
				<%= f.submit %>
			<% end %>
		</div>
	<% end %>

</div>

app/views/cards/_user_preview.html.erb
<% user = locals[:user] %>
<% this_table = 'users' %>
<% this_model = this_table.singularize %>

<div class="profile-wrapper">

	<% if user.avatar.exists? %>
		<%= image_tag user.avatar.url, class: 'user-profile-pic left' %>
	<% end %>

	<div class="user-bio left">

		<h1 class="users-editable" 
			contenteditable="<%= editable_if_admin(user) %>"
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-id=<%= user.id %>
			data-attribute='intro'>
			<%= user.intro || 'Headline here' %>
		</h1>

		<% intro = user.intro_paragraph || '<p>More about you here</p>' %>
		<div class="users-editable" 
			contenteditable="<%= editable_if_admin(user) %>"
			data-table="<%= this_table %>"
			data-model="<%= this_model %>"
			data-id=<%= user.id %>
			data-attribute='intro_paragraph'>
			<%= raw(intro) %>
		</div>

	</div>

	<div class="profile-action-items left">
		<%= link_to "Preapprove for Interview", '#' %>
		<%= link_to "Message Me", '#' %>
		<%= link_to "Howl At Me", '#' %>

		<div class="social-icons">
			<i class="fa fa-git"></i>
			<i class="fa fa-facebook"></i>
			<i class="fa fa-linkedin"></i>		
			<i class="fa fa-twitter"></i>
		</div>
	</div>
</div>